#$language = "VBScript"
#$interface = "1.0"

crt.Screen.Synchronous = True

Sub Main
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0001ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0101ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0201ff00" & chr(13)
	crt.Sleep(500)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0301ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0401ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0501ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0601ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0701ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0800ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "U FFFFFFFF0901ff00" & chr(13)
	crt.Screen.WaitForString "Update Transmit Packet? Are You Sure? [y/N] "
	crt.Sleep(500)
	crt.Screen.Send "y" & chr(13)
	crt.Sleep(500)
	crt.Screen.Send "t" & chr(13)
End Sub
